/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-06-17 15:07:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"/>\n");
      out.write("<title>�ラ��绯荤�</title>\n");
      out.write("<link rel=\"shortcut icon\" href=\"css/favicon.ico\"/> \n");
      out.write("<link rel=\"stylesheet\" href=\"css/expenseLinko.css\" type=\"text/css\"/>\n");
      out.write("<!--[if IE 7]> <link rel=\"stylesheet\" href=\"expenseLinko_ie7.css\" type=\"text/css\" media=\"screen\" /> <![endif]-->\n");
      out.write("<!--[if IE 8]> <link rel=\"stylesheet\" href=\"expenseLinko_ie8.css\" type=\"text/css\" media=\"screen\" /> <![endif]-->\r\n");
      out.write("<!--[if IE 9]> <link rel=\"stylesheet\" href=\"expenseLinko_ie8.css\" type=\"text/css\" media=\"screen\" /> <![endif]-->\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".adminLink\r\n");
      out.write("{\r\n");
      out.write("  line-height:10px;\r\n");
      out.write("  float:right;\r\n");
      out.write("}  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body >\n");
      out.write("\n");
      out.write("<div id=\"infoLogin\">\r\n");
      out.write("\r\n");
      out.write("<br><label for=\"email\">Welcome to ESS&trade;</label>\r\n");
      out.write("<br>\n");
      out.write("  <form method=\"post\" action=\"login.do\">       \n");
      out.write("       \n");
      out.write("      <label for=\"username\">�ㄦ�峰��</label>\n");
      out.write("      <input id=\"username\" type=\"text\" name=\"username\" />\n");
      out.write("      <label for=\"password\">瀵���</label>\n");
      out.write("      <input id=\"password\" type=\"password\" name=\"password\" />\n");
      out.write("      <input id=\"btEnter\" type=\"submit\" value=\"Login\" name=\"B1\">\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
