/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-07-16 14:17:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/header.jsp", Long.valueOf(1436452194103L));
    _jspx_dependants.put("/WEB-INF/jsp/footer.jsp", Long.valueOf(1436716181451L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<title>J2EE人力资源系统</title>\r\n");
      out.write("<link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body topmargin=\"0\"><table width=\"780\" height=\"110\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/bodybg.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"100\" height=\"94\" rowspan=\"2\"><img src=\"images/logo.jpg\" width=\"94\" height=\"94\" align=\"right\"></td>\r\n");
      out.write("\t\r\n");
      out.write("    <td width=\"577\" height=\"65\"><div align=\"center\"><font size=\"+2\" color=\"#CC6600\"><b>J2EE人力资源系统</b></font></div></td>\r\n");
      out.write("    <td width=\"103\" rowspan=\"2\"><img src=\"images/logo.jpg\" width=\"94\" height=\"94\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"15\"><div align=\"center\" class=\"title\">如果需要开发高档的J2EE应用，请联系<a href=\"mailto:kongyeeku@163.com\">kongyeeku@163.com</a>。谢谢</div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"5\" colspan=\"3\"><hr></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write(" \r\n");
      out.write("<TABLE width=780 align=\"center\" CELLSPACING=0 background=\"images/bodybg.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"3\">请单击后面链接开始使用系统<a href=\"login.do\">登陆系统</a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <TR> \r\n");
      out.write("    <TD colspan=\"3\" valign=TOP> \r\n");
      out.write("\t<br>\r\n");
      out.write("      <p align=\"center\"><span class=\"pt9\">这仅仅是一个J2EE的框架程序。应用模拟一个电子人力管理系统。系统包含两个角色，<br>\r\n");
      out.write("        普通员工的功能包括员工出勤打卡，员工的人事异动申请，员工查看工资单。<br>\r\n");
      out.write("        经理的功能包括管理部门员工，签核申请，每月工资自动结算等。</span></p>      \r\n");
      out.write("      <p align=\"center\" class=\"pt9\">应用模拟了简单的工作流，使用的轻量级J2EE架构。技术包括：Struts,Spring,Hibernate<br>\r\n");
      out.write("      Quartz,整个应用使用Spring提供的DAO支持操作数据库,同时利用Spring的声明式事务。<br>\r\n");
      out.write("      程序中的权限检查使用Spring的AOP框架支持，也利用了Spring的任务调度抽象<br>\r\n");
      out.write("\t  Hibernate为底层的数据库访问提供支持,作为O/R Mapping框架使用。</p>\r\n");
      out.write("      <p align=\"center\" class=\"pt9\">应用的测试框架采用Spring与JUnit结合。</p>\r\n");
      out.write("      <p align=\"center\"><span class=\"pt9\">本程序的源代码随程序一起发布，版权属于李刚，kongyeeku@163.com<br>\r\n");
      out.write("      任何个人可用来参考学习J2EE架构，规范，但请勿在本程序的基础上修改，用做任何商业用途。<br>\r\n");
      out.write("      本人保留依法追究相关责任的权利。转载和学习请保留此信息。\r\n");
      out.write("      <br>\r\n");
      out.write("    </p>    </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<table width=\"780\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td background=\"images/bodybg.jpg\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\t\r\n");
      out.write("\t\t  <TR>\r\n");
      out.write("\t\t\t<TD width=\"283\" valign=TOP><img src=\"images/struts.gif\" width=\"188\" height=\"66\"></TD>\r\n");
      out.write("\t\t\t<TD width=\"246\" valign=TOP><img src=\"images/spring.gif\" width=\"152\" height=\"66\"></TD>\r\n");
      out.write("\t\t\t<TD width=\"243\" valign=TOP><img src=\"images/hibernate.png\" width=\"203\" height=\"56\"></TD>\r\n");
      out.write("\t\t  </TR>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"68\" background=\"images/bodybg.jpg\">   <div align=\"center\" class=\"pt9\">\r\n");
      out.write("      All Rights Reserved.<br>\r\n");
      out.write("      版权所有 Copyright@2006 Yeeku.H.Lee <BR>\r\n");
      out.write("    如有任何问题和建议，<A href=\"mailto:kongyeeku@163.com\">请E-mail to me</A>！<BR>\r\n");
      out.write("    建议您使用1024*768分辨率，IE5.0以上版本使用本系统!</p>\r\n");
      out.write("    </div>    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height=\"5\"><td background=\"images/bottom.jpg\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
