/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.61
 * Generated at: 2015-07-20 15:56:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.employee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class expense_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/employee/../taglibs.jsp", Long.valueOf(1436452194108L));
    _jspx_dependants.put("/WEB-INF/jsp/employee/../footer.jsp", Long.valueOf(1436716181451L));
    _jspx_dependants.put("/WEB-INF/struts-logic.tld", Long.valueOf(1436452194217L));
    _jspx_dependants.put("/WEB-INF/struts-html.tld", Long.valueOf(1436452194217L));
    _jspx_dependants.put("/WEB-INF/jsp/employee/empheader.jsp", Long.valueOf(1436716190382L));
    _jspx_dependants.put("/WEB-INF/struts-bean.tld", Long.valueOf(1436452194216L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>J2EE人力资源系统</title> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".reportSection{background-color:#33FFFF; border:1px solid #DDDDDD; padding:24px 12px 24px 12px; background-image:url(img_background_form.gif); background-position:bottom; background-repeat:repeat-x; margin: 40px 0 0 0; width:961px;}\r\n");
      out.write(".titleForm{ background-color:#00FF33; border:1px solid #CCCCCC; color:#333366; font-size:14px; font-weight:bold; margin:0; padding:6px 15px 4px 15px; position:absolute; margin-top:-44px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body topmargin=\"0\"><table width=\"780\" height=\"110\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/bodybg.jpg\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"100\" height=\"94\" rowspan=\"2\"><img src=\"images/logo.jpg\" width=\"94\" height=\"94\" align=\"right\"></td>\r\n");
      out.write("\t\r\n");
      out.write("    <td width=\"577\" height=\"65\"><div align=\"center\"><font size=\"+2\" color=\"#CC6600\"><b>J2EE人力资源系统</b></font></div></td>\r\n");
      out.write("    <td width=\"103\" rowspan=\"2\"><img src=\"images/logo.jpg\" width=\"94\" height=\"94\"></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"5\" colspan=\"3\"><hr></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"3\">\r\n");
      out.write("\t\t<table width=\"60%\">\r\n");
      out.write("\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><a href=\"expense.do\">我要报销</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"viewExpenseEmp.do\">查看我的报销</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"logout.do\">退出系统</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<form action=\"doExpense.do?method=woshishui\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"expenseItem\">\r\n");
      out.write("费用产生时间： <input class=\"easyui-datebox\" name=\"didDate\" id=\"begindate\" data-options=\"formatter:myformatter,parser:myparser\"></input>\r\n");
      out.write("费用的目的：<input type=\"text\" name=\"purpose\" value=\"\"/>\r\n");
      out.write("费用的金额: <input type=\"text\" name=\"num\" value=\"\"/>\r\n");
      out.write("提交发票:   <input type=\"file\" name=\"file\" value=\"浏览\"/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"button\" name=\"\" value=\"添加新的报销项\" onClick=\"addNewExpenseItem()\"/>\r\n");
      out.write("<input type=\"submit\" name=\"submit\" value=\"提交\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<table width=\"780\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td background=\"images/bodybg.jpg\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\t\r\n");
      out.write("\t\t  <TR>\r\n");
      out.write("\t\t\t<TD width=\"283\" valign=TOP><img src=\"images/struts.gif\" width=\"188\" height=\"66\"></TD>\r\n");
      out.write("\t\t\t<TD width=\"246\" valign=TOP><img src=\"images/spring.gif\" width=\"152\" height=\"66\"></TD>\r\n");
      out.write("\t\t\t<TD width=\"243\" valign=TOP><img src=\"images/hibernate.png\" width=\"203\" height=\"56\"></TD>\r\n");
      out.write("\t\t  </TR>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td height=\"68\" background=\"images/bodybg.jpg\">   <div align=\"center\" class=\"pt9\">\r\n");
      out.write("      All Rights Reserved.<br>\r\n");
      out.write("      版权所有 Copyright@2006 Yeeku.H.Lee <BR>\r\n");
      out.write("    如有任何问题和建议，<A href=\"mailto:kongyeeku@163.com\">请E-mail to me</A>！<BR>\r\n");
      out.write("    建议您使用1024*768分辨率，IE5.0以上版本使用本系统!</p>\r\n");
      out.write("    </div>    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr height=\"5\"><td background=\"images/bottom.jpg\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function addNewExpenseItem(){\r\n");
      out.write("\tvar expItem = document.getElementById(\"expenseItem\");\r\n");
      out.write("\tvar cloneExpItem = expItem.cloneNode(true);\r\n");
      out.write("\tcloneExpItem.setAttribute(\"id\",\"expenseItem1\")\r\n");
      out.write("\texpItem.appendChild(cloneExpItem);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function myformatter(date) {\r\n");
      out.write("\tvar y = date.getFullYear();\r\n");
      out.write("    var m = date.getMonth() + 1;\r\n");
      out.write("    var d = date.getDate();\r\n");
      out.write("    return y + '-' + (m < 10 ? ('0' + m) : m) + '-'\r\n");
      out.write("        + (d < 10 ? ('0' + d) : d);\r\n");
      out.write("}\r\n");
      out.write("function myparser(s) {\r\n");
      out.write("if (!s)\r\n");
      out.write("return new Date();\r\n");
      out.write("var ss = (s.split('-'));\r\n");
      out.write("var y = parseInt(ss[0], 10);\r\n");
      out.write("var m = parseInt(ss[1], 10);\r\n");
      out.write("var d = parseInt(ss[2], 10);\r\n");
      out.write("if (!isNaN(y) && !isNaN(m) && !isNaN(d)) {\r\n");
      out.write("return new Date(y, m - 1, d);\r\n");
      out.write("} else {\r\n");
      out.write("return new Date();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
